[theme]
primaryColor = "#e5b94f"
backgroundColor = "#080d2b"
secondaryBackgroundColor = "#111944"
textColor = "#f7f4ea"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 10
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false
