GOOGLE_CLIENT_ID = "619153433376-lukkhcoucrmj77sjgp486r253h4v4mgv.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://jayopardy.streamlit.app/"
OAUTH_COMPONENT_REDIRECT_URI = "https://share.streamlit.io/component/streamlit_oauth.authorize_button/index.html"

# Cloudflare R2 configuration (fill in your real credentials or leave blank for env vars)
R2_ENDPOINT_URL = ""
R2_ACCESS_KEY = ""
R2_SECRET_KEY = ""
R2_BUCKET_NAME = "jeopardy-dataset"
R2_FILE_KEY = "all_jeopardy_clues.csv"
