GOOGLE_CLIENT_ID = "619153433376-lukkhcoucrmj77sjgp486r253h4v4mgv.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://jayopardy.streamlit.app/"
REDIRECT_URI = "https://share.streamlit.io/component/streamlit_oauth.authorize_button/index.html"
