GOOGLE_CLIENT_ID = "619153433376-lukkhcoucrmj77sjgp486r253h4v4mgv.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://jayopardy.streamlit.app/"
REDIRECT_URI = "https://share.streamlit.io/component/streamlit_oauth.authorize_button/index.html"

# Firebase Configuration (Complete)
firebase_project_id = "jaypardy-53a55"
firebase_api_key = "AIzaSyD7OcmmwWY6zV4ngPHjsdwxvoXJ41r55UM"
firebase_auth_domain = "jaypardy-53a55.firebaseapp.com"
firebase_storage_bucket = "jaypardy-53a55.appspot.com"
firebase_messaging_sender_id = "367259134434"
firebase_app_id = "1:367259134434:web:5728976d5fba3ef022b1bb"
firebase_database_url = "https://jaypardy-53a55-default-rtdb.firebaseio.com"

# Service Account (still needed - get from Firebase Console)
firebase_type = "service_account"
firebase_private_key_id = "YOUR_PRIVATE_KEY_ID"
firebase_private_key = "YOUR_PRIVATE_KEY"
firebase_client_email = "firebase-adminsdk-xxxxx@jaypardy-53a55.iam.gserviceaccount.com"
firebase_client_id = "YOUR_CLIENT_ID"
